"""support multiselect product attributes

Revision ID: 109e67269602
Revises: 7792ce79a671
Create Date: 2026-09-24 22:13:21.619847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109e67269602'
down_revision: Union[str, Sequence[str], None] = '7792ce79a671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_product_attribute_values_product_attribute'), 'product_attribute_values', type_='unique')
    op.create_index('uq_product_attribute_values_product_attribute_option', 'product_attribute_values', ['product_id', 'attribute_id', 'attribute_option_id'], unique=True, postgresql_where=sa.text('attribute_option_id IS NOT NULL'), sqlite_where=sa.text('attribute_option_id IS NOT NULL'))
    op.create_index('uq_product_attribute_values_product_attribute_scalar', 'product_attribute_values', ['product_id', 'attribute_id'], unique=True, postgresql_where=sa.text('attribute_option_id IS NULL'), sqlite_where=sa.text('attribute_option_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_product_attribute_values_product_attribute_scalar', table_name='product_attribute_values', postgresql_where=sa.text('attribute_option_id IS NULL'), sqlite_where=sa.text('attribute_option_id IS NULL'))
    op.drop_index('uq_product_attribute_values_product_attribute_option', table_name='product_attribute_values', postgresql_where=sa.text('attribute_option_id IS NOT NULL'), sqlite_where=sa.text('attribute_option_id IS NOT NULL'))
    op.create_unique_constraint(op.f('uq_product_attribute_values_product_attribute'), 'product_attribute_values', ['product_id', 'attribute_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
