"""add pricing warranty promotions and product serials

Revision ID: 145b99f39edb
Revises: b71d4c9e2a10
Create Date: 2026-10-06 10:16:50.024838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145b99f39edb'
down_revision: Union[str, Sequence[str], None] = 'b71d4c9e2a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to >= valid_from', name='ck_promotions_valid_dates'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_price >= 0', name='ck_product_prices_cost_price_nonnegative'),
    sa.CheckConstraint('minimum_sale_price IS NULL OR minimum_sale_price <= sale_price', name='ck_product_prices_minimum_lte_sale'),
    sa.CheckConstraint('minimum_sale_price IS NULL OR minimum_sale_price >= 0', name='ck_product_prices_minimum_sale_price_nonnegative'),
    sa.CheckConstraint('sale_price >= 0', name='ck_product_prices_sale_price_nonnegative'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_product_prices_valid_dates'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_serial_numbers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='IN_STOCK', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('IN_STOCK', 'RESERVED', 'SOLD')", name='ck_product_serial_numbers_status'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'serial_number', name='uq_product_serial_numbers_tenant_serial')
    )
    op.create_table('promotion_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('selection_rule', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("selection_rule IN ('REQUIRED', 'ONE', 'ALL', 'OPTIONAL')", name='ck_promotion_groups_selection_rule'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_products',
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('promotion_id', 'product_id', name='pk_promotion_products')
    )
    op.create_table('warranty_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('additional_months', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('additional_months > 0', name='ck_warranty_options_additional_months_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_benefits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promotion_group_id', sa.Integer(), nullable=False),
    sa.Column('benefit_type', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('warranty_option_id', sa.Integer(), nullable=True),
    sa.Column('promotion_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cashback_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                benefit_type = 'PRODUCT'\n                AND product_id IS NOT NULL\n                AND warranty_option_id IS NULL\n                AND promotion_price IS NOT NULL\n                AND cashback_amount IS NULL\n                AND payment_mode IS NULL\n            )\n            OR\n            (\n                benefit_type = 'WARRANTY'\n                AND product_id IS NULL\n                AND warranty_option_id IS NOT NULL\n                AND promotion_price IS NOT NULL\n                AND cashback_amount IS NULL\n                AND payment_mode IS NULL\n            )\n            OR\n            (\n                benefit_type = 'CASHBACK'\n                AND product_id IS NULL\n                AND warranty_option_id IS NULL\n                AND promotion_price IS NULL\n                AND cashback_amount IS NOT NULL\n                AND payment_mode IS NOT NULL\n            )\n            ", name='ck_promotion_benefits_valid_type_fields'),
    sa.CheckConstraint("benefit_type IN ('PRODUCT', 'WARRANTY', 'CASHBACK')", name='ck_promotion_benefits_type'),
    sa.CheckConstraint('cashback_amount IS NULL OR cashback_amount >= 0', name='ck_promotion_benefits_cashback_nonnegative'),
    sa.CheckConstraint('promotion_price IS NULL OR promotion_price >= 0', name='ck_promotion_benefits_price_nonnegative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['promotion_group_id'], ['promotion_groups.id'], ),
    sa.ForeignKeyConstraint(['warranty_option_id'], ['warranty_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warranty_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warranty_option_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_warranty_prices_price_nonnegative'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_warranty_prices_valid_dates'),
    sa.ForeignKeyConstraint(['warranty_option_id'], ['warranty_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('products', sa.Column('default_warranty_months', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('products', sa.Column('requires_serial_number', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'requires_serial_number')
    op.drop_column('products', 'default_warranty_months')
    op.drop_column('categories', 'gst_rate')
    op.drop_table('warranty_prices')
    op.drop_table('promotion_benefits')
    op.drop_table('warranty_options')
    op.drop_table('promotion_products')
    op.drop_table('promotion_groups')
    op.drop_table('product_serial_numbers')
    op.drop_table('product_prices')
    op.drop_table('promotions')
    # ### end Alembic commands ###
