"""add inventory tables

Revision ID: 7792ce79a671
Revises: ee9528c79c08
Create Date: 2026-09-24 16:56:59.717641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7792ce79a671'
down_revision: Union[str, Sequence[str], None] = 'ee9528c79c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('godown_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(store_id IS NOT NULL) <> (godown_id IS NOT NULL)', name='ck_inventory_exactly_one_location'),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity_nonnegative'),
    sa.CheckConstraint('reserved_quantity <= quantity', name='ck_inventory_reserved_quantity_lte_quantity'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_inventory_reserved_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_tenant_id', 'inventory', ['tenant_id'], unique=False)
    op.create_index('uq_inventory_tenant_product_godown', 'inventory', ['tenant_id', 'product_id', 'godown_id'], unique=True, postgresql_where=sa.text('godown_id IS NOT NULL'))
    op.create_index('uq_inventory_tenant_product_store', 'inventory', ['tenant_id', 'product_id', 'store_id'], unique=True, postgresql_where=sa.text('store_id IS NOT NULL'))
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('from_store_id', sa.Integer(), nullable=True),
    sa.Column('from_godown_id', sa.Integer(), nullable=True),
    sa.Column('to_store_id', sa.Integer(), nullable=True),
    sa.Column('to_godown_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("movement_type IN ('OPENING', 'TRANSFER', 'SALE', 'ADJUSTMENT', 'RESERVATION', 'RELEASE')", name='ck_inventory_movements_movement_type'),
    sa.CheckConstraint('quantity > 0', name='ck_inventory_movements_quantity_positive'),
    sa.ForeignKeyConstraint(['from_godown_id'], ['godowns.id'], ),
    sa.ForeignKeyConstraint(['from_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['performed_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['to_godown_id'], ['godowns.id'], ),
    sa.ForeignKeyConstraint(['to_store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_movements_created_at', 'inventory_movements', ['created_at'], unique=False)
    op.create_index('ix_inventory_movements_movement_type', 'inventory_movements', ['movement_type'], unique=False)
    op.create_index('ix_inventory_movements_product_id', 'inventory_movements', ['product_id'], unique=False)
    op.create_index('ix_inventory_movements_tenant_id', 'inventory_movements', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_movements_tenant_id', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_product_id', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_movement_type', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_created_at', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('uq_inventory_tenant_product_store', table_name='inventory', postgresql_where=sa.text('store_id IS NOT NULL'))
    op.drop_index('uq_inventory_tenant_product_godown', table_name='inventory', postgresql_where=sa.text('godown_id IS NOT NULL'))
    op.drop_index('ix_inventory_tenant_id', table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
