"""add sale items

Revision ID: dc7e4038149e
Revises: f51b092803f3
Create Date: 2026-10-06 20:10:29.912125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7e4038149e'
down_revision: Union[str, Sequence[str], None] = 'f51b092803f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('configured_unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_unit_price >= 0', name='ck_sale_items_actual_price_nonnegative'),
    sa.CheckConstraint('configured_unit_price >= 0', name='ck_sale_items_configured_price_nonnegative'),
    sa.CheckConstraint('cost_price >= 0', name='ck_sale_items_cost_price_nonnegative'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_sale_items_discount_nonnegative'),
    sa.CheckConstraint('gst_amount >= 0', name='ck_sale_items_gst_amount_nonnegative'),
    sa.CheckConstraint('gst_rate >= 0', name='ck_sale_items_gst_rate_nonnegative'),
    sa.CheckConstraint('line_total >= 0', name='ck_sale_items_line_total_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='ck_sale_items_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_items')
    # ### end Alembic commands ###
